version: "3.9"

services:
  db:
    image: postgres:13
    container_name: social-media-scheduler-db
    environment:
      POSTGRES_USER: shereef
      POSTGRES_PASSWORD: password
      POSTGRES_DB: social-media-scheduler
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: social-media-scheduler-api
    working_dir: /app
    volumes:
      - ./backend:/app/backend  # ✅ Ensures backend folder is correctly mapped
    command: uvicorn backend.app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data: